apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z6v7qt5e7-python
  janus-idp.io/tekton: z6v7qt5e7-python
  backstage.io/kubernetes-id: z6v7qt5e7-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z6v7qt5e7-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
